---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:20.04
    dockerfile: Dockerfile.j2
    pre_build_image: false
provisioner:
  name: ansible
verifier:
  name: ansible
