---
# vars file for guardian

public_guardian_list:
  - name: Cube Exchange Temp Guardian 201
    guardian_id: 201
    public_fqdn: guardian-201.testing.cube.exchange
    public_port_node: 20101
    public_port_web: 20441
  - name: Cube Exchange Temp Guardian 202
    guardian_id: 202
    public_fqdn: guardian-202.testing.cube.exchange
    public_port_node: 20102
    public_port_web: 20442
  - name: Cube Exchange Temp Guardian 203
    guardian_id: 203
    public_fqdn: guardian-203.testing.cube.exchange
    public_port_node: 20103
    public_port_web: 20443
  - name: Cube Exchange Temp Guardian 208
    guardian_id: 208
    public_fqdn: rick.guardian-test.cube.exchange
    public_port_node: 20108
    public_port_web: 443
  - name: Cube Exchange Temp Guardian 209
    guardian_id: 209
    public_fqdn: xi.guardian-testing.cube.exchange
    public_port_node: 20109
    public_port_web: 443
