- name: Deploy Hashicorp Vault Cluster
  # Update hosts selector with new inventory group name of Vault Cluster Hosts
  hosts: example_hashicorp_vault_cluster
  gather_facts: false
  become: true
  become_user: root
  roles:
    - geerlingguy.swap
    - cubexch.guardian.hashicorp_vault_cluster
