- name: Generate Self-Signed Certificates Locally
  hosts: example_hashicorp_vault_cluster
  gather_facts: false
  become: false
  tasks:
    - name: Create self_signed_certs_local_dir
      delegate_to: localhost
      ansible.builtin.file:
        dest: '{{ self_signed_certs_local_dir }}'
        state: directory
        mode: 'u+rw,g+r,o=-'
      tags:
        - generate_self_signed_certs

    - name: Generate Self Signed Certs
      delegate_to: localhost
      ansible.builtin.command:
        cmd: '{{ playbook_dir }}/files/generate_self_signed_certs.sh {{ fqdn_suffix }} {{ item }} {{ self_signed_certs_local_dir }}'
        chdir: '{{ self_signed_certs_local_dir }}'
      with_items:
        - '{{ groups[hashicorp_vault_cluster_group_name] }}'
      tags:
        - generate_self_signed_certs
