---
# tasks file for get_approles_guardian

- name: Get AppRole Role ID - Guardian Reader
  no_log: true
  community.hashi_vault.vault_read:
    url: "{{ vault_url }}"
    path: "auth/approle/role/cube-guardian-{{ item.guardian_id }}.reader/role-id"
    auth_method: "token"
    token: "{{ loaded_vault_init_data.root_token }}"
    ca_cert: "{{ vault_ca_cert_path }}"
  ignore_errors: true # TODO: Check for existence before enabling, it causes an exception if path already exists.
  register: guardian_reader_role_id

- name: Get AppRole Secret ID - Guardian Reader
  no_log: true
  community.hashi_vault.vault_write:
    url: "{{ vault_url }}"
    path: "auth/approle/role/cube-guardian-{{ item.guardian_id }}.reader/secret-id"
    auth_method: "token"
    token: "{{ loaded_vault_init_data.root_token }}"
    ca_cert: "{{ vault_ca_cert_path }}"
  ignore_errors: true # TODO: Check for existence before enabling, it causes an exception if path already exists.
  register: guardian_reader_secret_id

- name: Create Vault Reader JSON
  no_log: true
  ansible.builtin.set_fact:
    guardian_reader_approle_credentials:
      role_id: '{{ guardian_reader_role_id.data.data.role_id }}'
      secret_id: '{{ guardian_reader_secret_id.data.data.secret_id }}'

- name: Write AppRole Credentials - Guardian Reader
  no_log: true
  ansible.builtin.copy:
    content: "{{ guardian_reader_approle_credentials | to_json(indent=4, sort_keys=true) }}"
    dest: "{{ cube_vault_configs_dir }}/vault.guardian.{{ item.guardian_hostname }}.reader.json"
    owner: "root"
    group: "root"
    mode: u=rw,go=-

- name: Get AppRole Role ID - Guardian Writer
  no_log: true
  community.hashi_vault.vault_read:
    url: "{{ vault_url }}"
    path: "auth/approle/role/cube-guardian-{{ item.guardian_id }}.writer/role-id"
    auth_method: "token"
    token: "{{ loaded_vault_init_data.root_token }}"
    ca_cert: "{{ vault_ca_cert_path }}"
  ignore_errors: true # TODO: Check for existence before enabling, it causes an exception if path already exists.
  register: guardian_writer_role_id

- name: Get AppRole Secret ID - Guardian Reader
  no_log: true
  community.hashi_vault.vault_write:
    url: "{{ vault_url }}"
    path: "auth/approle/role/cube-guardian-{{ item.guardian_id }}.writer/secret-id"
    auth_method: "token"
    token: "{{ loaded_vault_init_data.root_token }}"
    ca_cert: "{{ vault_ca_cert_path }}"
  ignore_errors: true # TODO: Check for existence before enabling, it causes an exception if path already exists.
  register: guardian_writer_secret_id

- name: Create Vault Reader JSON
  no_log: true
  ansible.builtin.set_fact:
    guardian_writer_approle_credentials:
      role_id: '{{ guardian_writer_role_id.data.data.role_id }}'
      secret_id: '{{ guardian_writer_secret_id.data.data.secret_id }}'

- name: Write AppRole Credentials - Guardian Writer
  no_log: true
  ansible.builtin.copy:
    content: "{{ guardian_writer_approle_credentials | to_json(indent=4, sort_keys=true) }}"
    dest: "{{ cube_vault_configs_dir }}/vault.guardian.{{ item.guardian_hostname }}.writer.json"
    owner: "root"
    group: "root"
    mode: u=rw,go=-
