### Option to create /etc/hosts entries ###
# Option to create /etc/hosts entries for each cluster member
create_etc_hosts_entries: true

### Required Inventory Variables when creating /etc/hosts entries ###
# Select an interface to get an IP address from when creating /etc/hosts entries
#
## Select the default interface detected by ansible
# hashicorp_vault_interface_api_interface: "{{ ansible_default_ipv4.interface }}"
## Or specify an interface name
hashicorp_vault_interface_api_interface: 'bond0'
# hashicorp_vault_interface_api_ip: "{{ hostvars[inventory_hostname]['ansible_' ~ hashicorp_vault_interface_api_interface]['ipv4']['address'] }}"
###########################################

# Inventory Group Name for your Hashicorp Vault Cluster
hashicorp_vault_cluster_group_name: 'example_hashicorp_vault_cluster'

# FQDN suffix to use for each host (i.e. example-vault-1.vault.example.com)
vault_cluster_fqdn: 'hashicorp-vault.testing.cube.exchange'
hashicorp_vault_cluster_name: 'example-guardian-vault'

# Port used for API communications to the cluster
hashicorp_vault_cluster_port_api: 8200
# Port used for internal cluster node-to-node communication
hashicorp_vault_cluster_port_cluster: 8201

# Optional: Open Firewall Rules with iptables
open_iptables: true
open_iptables_source_network_api_port: '127.0.0.0/24'
open_iptables_source_network_cluster_port: '127.0.0.0/24'

self_signed_certs_generate: true
self_signed_certs_local_dir: '{{ inventory_dir }}/hashicorp-vault-certs'

hashicorp_vault_init_data_local_dir: '{{ inventory_dir }}/hashicorp-vault-init'
